### ISSUE TITLE
fancybox关不掉

### ISSUE THREAD

**Issue by qingtingxianzhang** [xbmlz/hexo-theme-maple#1]

**Comment by qingtingxianzhang** [comment]
可以看 [shuo.at](https://shuo.at/2022/08/16/microtherm-charge-plan/)

**Comment by MakeAToast** [comment]
看起来是fancybox的判断没加，我手动去掉了

head.ejs #42
after-footer.ejs #25

图片大小还是存在问题，我再看看怎么搞。

**Comment by qingtingxianzhang** [comment]
看起来是fancybox的判断没加，我手动去掉了

head.ejs #42
after-footer.ejs #25

图片大小还是存在问题，我再看看怎么搞。

**Comment by qingtingxianzhang** [comment]
文章图片大小的问题解决了

在post的css里加了
  img
    max-width: 100%
    height: auto

**Comment by xbmlz** [comment]
> 文章图片大小的问题解决了
> 
> 在post的css里加了 img max-width: 100% height: auto

建议更新最新版，已全方位优化，颜值也有很大提升哦
