### ISSUE TITLE
首页无页码切换, 文章不显示Category标签

### ISSUE THREAD

**Issue by liunaijie** [xbmlz/hexo-theme-maple#10]
Hi, 我发现这个主题非常干净简洁,并且支持数学公式显示, 今天切换到这个主题试了一下, 发现了一丢丢小问题
1. 没有页码切换功能, 只能通过文章中的上一篇/下一篇来进行切换
2. 在文章中只有Tag信息, 没有显示Category信息
3. 我之前的主题中, 使用 `<!--more-->`这个关键字来进行控制文章在外面显示的内容, 发现在这个主题内, 在外面的简介中会添加`<p><br>`这种符号, 而且打开文章后, `<!--more-->`之前的内容会显示两遍.
4. 文章底部留白太大, 拉到底部后还能向下拉动很大一部分.

**Comment by xbmlz** [comment]
> Hi, 我发现这个主题非常干净简洁,并且支持数学公式显示, 今天切换到这个主题试了一下, 发现了一丢丢小问题
> 
> 1. 没有页码切换功能, 只能通过文章中的上一篇/下一篇来进行切换
> 2. 在文章中只有Tag信息, 没有显示Category信息
> 3. 我之前的主题中, 使用 `<!--more-->`这个关键字来进行控制文章在外面显示的内容, 发现在这个主题内, 在外面的简介中会添加`<p><br>`这种符号, 而且打开文章后, `<!--more-->`之前的内容会显示两遍.
> 4. 文章底部留白太大, 拉到底部后还能向下拉动很大一部分.

感谢你的支持，你提出的大部分问题已在最新版本修复 ^_^

https://github.com/xbmlz/hexo-theme-maple/releases

DEMO: https://xbmlz.github.io/

**Comment by liunaijie** [comment]
> > Hi, 我发现这个主题非常干净简洁,并且支持数学公式显示, 今天切换到这个主题试了一下, 发现了一丢丢小问题
> > 
> > 1. 没有页码切换功能, 只能通过文章中的上一篇/下一篇来进行切换
> > 2. 在文章中只有Tag信息, 没有显示Category信息
> > 3. 我之前的主题中, 使用 `<!--more-->`这个关键字来进行控制文章在外面显示的内容, 发现在这个主题内, 在外面的简介中会添加`<p><br>`这种符号, 而且打开文章后, `<!--more-->`之前的内容会显示两遍.
> > 4. 文章底部留白太大, 拉到底部后还能向下拉动很大一部分.
> 
> 感谢你的支持，你提出的大部分问题已在最新版本修复 ^_^
> 
> https://github.com/xbmlz/hexo-theme-maple/releases
> 
> DEMO: https://xbmlz.github.io/

Cool

**Comment by liunaijie** [comment]
大佬能给加一下页码显示以及切换吗 就这种
![image](https://github.com/xbmlz/hexo-theme-maple/assets/28497357/7045dcaf-5bc0-4f38-b537-7f3b323ef0be)
